---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart traefik
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: "{{ svc_compose_dir }}/traefik"

- name: Restart authentik
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: "{{ svc_compose_dir }}/authentik"

- name: Restart unifi
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: "{{ svc_compose_dir }}/unifi"

- name: Restart homepage
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: "{{ svc_compose_dir }}/homepage"
