---
- name: PBS | System
  ansible.builtin.import_tasks: system.yml
  tags: [system]

- name: PBS | Networking and Hardening
  ansible.builtin.import_tasks: network.yml
  tags: [network]

- name: PBS | Datastore
  ansible.builtin.import_tasks: datastore.yml
  tags: [datastore]

- name: PBS | Users
  ansible.builtin.import_tasks: users.yml
  tags: [users]

- name: PBS | Notification configuration
  ansible.builtin.import_tasks: notifications.yml
  tags: [notifications]

