---
- name: PBS | Download Proxmox archive keyring
  ansible.builtin.get_url:
    url: "https://enterprise.proxmox.com/debian/proxmox-archive-keyring-{{ proxmox_debian_release }}.gpg"
    dest: /usr/share/keyrings/proxmox-archive-keyring.gpg
    mode: "0644"

- name: PBS | Add no-subscription repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pbs.sources
    mode: "0644"
    content: |
      Types: deb
      URIs: http://download.proxmox.com/debian/pbs
      Suites: {{ proxmox_debian_release }}
      Components: pbs-no-subscription
      Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg

- name: PBS | Remove enterprise and conflicting repositories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/pbs-enterprise.list
    - /etc/apt/sources.list.d/pbs-enterprise.sources
    - /etc/apt/sources.list.d/pbs.list
    - /etc/apt/sources.list.d/pbs-no-subscription.list

- name: PBS | Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: PBS | Install Proxmox Backup Server
  ansible.builtin.apt:
    name: proxmox-backup-server
    state: present

- name: PBS | Enable and start PBS service
  ansible.builtin.systemd:
    name: proxmox-backup
    enabled: true
    state: started
