---
teleport_config_path: /etc/teleport.yaml
teleport_data_dir: /var/lib/teleport
teleport_wildcard_domain: ""

# Ports
teleport_proxy_port: 443
teleport_ssh_proxy_port: 3022
teleport_reverse_tunnel_port: 3024
teleport_auth_port: 3025

# Config
teleport_session_recording: proxy

# Certbot
certbot_propagation_seconds: 30
