---
- name: Teleport Config | Write production config
  ansible.builtin.template:
    src: teleport.yaml.j2
    dest: "{{ teleport_config_path }}"
    owner: root
    group: root
    mode: "0600"
  vars:
    teleport_node_token: >-
      {{ lookup('amazon.aws.ssm_parameter', '/infra/teleport/node_token',
         with_decryption=true, profile=aws_profile, region=aws_region) }}
  notify: Restart teleport
  no_log: true
