---
- name: Teleport | ACME certificate
  ansible.builtin.import_tasks: acme.yml
  tags: [acme]

- name: Teleport | Node enrollment token
  ansible.builtin.import_tasks: nodes.yml
  tags: [nodes, config]

- name: Teleport | Configuration
  ansible.builtin.import_tasks: config.yml
  tags: [config]

- name: Teleport | Firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: [firewall]

- name: Teleport | Admin user
  ansible.builtin.import_tasks: users.yml
  tags: [users]
