---
- name: Teleport Users | Check if admin user exists
  ansible.builtin.command: tctl users ls
  register: _teleport_users
  changed_when: false

- name: Teleport Users | Create admin user
  ansible.builtin.command: >
    tctl users add {{ proxmox_user }}
    --roles=editor,access
    --logins={{ proxmox_user }},root
  register: _teleport_user_add
  changed_when: _teleport_user_add.rc == 0
  failed_when:
    - _teleport_user_add.rc != 0
    - "'already exists' not in _teleport_user_add.stderr"
  when: proxmox_user not in _teleport_users.stdout

- name: Teleport Users | Show invite link
  ansible.builtin.debug:
    msg: "{{ _teleport_user_add.stdout_lines }}"
  when:
    - proxmox_user not in _teleport_users.stdout
    - _teleport_user_add.rc == 0
