---
- name: Base | System packages and upgrades
  ansible.builtin.import_tasks: packages.yml

- name: Base | Admin user setup
  ansible.builtin.import_tasks: users.yml

- name: Base | Fail2ban
  ansible.builtin.import_tasks: fail2ban.yml

- name: Base | SSH hardening
  ansible.builtin.import_tasks: ssh.yml
